### ISSUE TITLE
Has anyone had the same problem?

### ISSUE THREAD

**Issue by xiyomuque** [kanjieater/ComicEater#3]
/mnt/i/comiceater-master/lib/logger.js:53
    format.label({ label: process?.pid.toString() }),
                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/i/comiceater-master/index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
error Command failed with exit code 1.

**Comment by kanjieater** [comment]
```
Also make sure the version of Node.js specified in the .nvmrc  (found in the project root) is installed. Currently this is 16.6.2. I recommend using [nvm](https://github.com/nvm-sh/nvm).
```

What version of node are you using?

**Comment by xiyomuque** [comment]
node -v shows 16.6.2. I also tried later versions. still get that error.

**Comment by kanjieater** [comment]
I can only find your issue with versions and installed packages being the wrong version.  https://github.com/HashLips/hashlips_art_engine/issues/424

I don't think this is an issue with ComicEater, as this is working fine for me right now & valid syntax. Try starting fresh. Download the repo, yarn install it on the right version, and let me know if that fixes it

**Comment by xiyomuque** [comment]
Yes, the root problem is that chaining doesn't work. I tried just now to start fresh and yarning it, getting the same log. I'll try again tommorow to get node to process chaining.

**Comment by xiyomuque** [comment]
Oh, I just found out when I run "sudo node" the version of node is 12.22.9 but when I run "node" the version is 16.6.2. So if I run just node inside ComicEater folder I get this error instead which is the reason I started trying sudo. 
➜  ComicEater git:(master) ✗ yarn main --vvv --configfile "ComicEater.yml" --MaintainCollection
yarn run v1.22.19
$ node index.js --vvv --configfile ComicEater.yml --MaintainCollection
/home/user/ComicEater/lib/files.js:181
    throw new Error(e);
          ^

Error: Error: Error: ENOENT: no such file or directory, open ''
    at readYMLFile (/home/user/ComicEater/lib/files.js:181:11)
    at async getConfig (/home/user/ComicEater/lib/config.js:69:22)
    at async parseCommands (/home/user/ComicEater/lib/cli.js:239:18)

**Comment by xiyomuque** [comment]
tried to reinstall everything incl. nvm, npm, node, yarn. still getting the same error like above with versions of node: 16, 18, 19.

**Comment by xiyomuque** [comment]
just writing "yarn..." instead of "sudo yarn..." helped resolve node version error.
